//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGELNorte.Resoluciones.Presentation {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UGELNorte.Resoluciones.Presentation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminacion de Resolucion satisfactoria.
        /// </summary>
        internal static string Delete_Satisfactorio_Mensaje {
            get {
                return ResourceManager.GetString("Delete_Satisfactorio_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminacion de Resolucion.
        /// </summary>
        internal static string Delete_Satisfactorio_Mensaje_Titulo {
            get {
                return ResourceManager.GetString("Delete_Satisfactorio_Mensaje_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porfavor revisar lo siguiente.
        /// </summary>
        internal static string Error_Mensaje_Cabecera {
            get {
                return ResourceManager.GetString("Error_Mensaje_Cabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Concepto es requerido.
        /// </summary>
        internal static string Registration_Concepto_Requerido {
            get {
                return ResourceManager.GetString("Registration_Concepto_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI es requerido.
        /// </summary>
        internal static string Registration_DNI_Requerido {
            get {
                return ResourceManager.GetString("Registration_DNI_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede registrar la Resolucion.
        /// </summary>
        internal static string Registration_Error_Mensaje {
            get {
                return ResourceManager.GetString("Registration_Error_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en Registro de Resolucion.
        /// </summary>
        internal static string Registration_Error_Mensaje_Titulo {
            get {
                return ResourceManager.GetString("Registration_Error_Mensaje_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Expediente Judicial es requerido.
        /// </summary>
        internal static string Registration_ExpedienteJudicial_Requerido {
            get {
                return ResourceManager.GetString("Registration_ExpedienteJudicial_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Nombre de la Institucion Educativa es requerido.
        /// </summary>
        internal static string Registration_IIEE_Requerido {
            get {
                return ResourceManager.GetString("Registration_IIEE_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Numero de Proyecto es requerido.
        /// </summary>
        internal static string Registration_NroProyecto_Requerido {
            get {
                return ResourceManager.GetString("Registration_NroProyecto_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Numero de Resolucion es requerido.
        /// </summary>
        internal static string Registration_NroResolucion_Requerido {
            get {
                return ResourceManager.GetString("Registration_NroResolucion_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Resolucion guardado satisfactoriamente.
        /// </summary>
        internal static string Registration_Satisfactorio_Mensaje {
            get {
                return ResourceManager.GetString("Registration_Satisfactorio_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Resolucion.
        /// </summary>
        internal static string Registration_Satisfactorio_Mensaje_Titulo {
            get {
                return ResourceManager.GetString("Registration_Satisfactorio_Mensaje_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Situacion es requerida.
        /// </summary>
        internal static string Registration_Situacion_Requerido {
            get {
                return ResourceManager.GetString("Registration_Situacion_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Tipo de Resolucion es requerido.
        /// </summary>
        internal static string Registration_TipoResolucion_Requerido {
            get {
                return ResourceManager.GetString("Registration_TipoResolucion_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Tipo de UGEL es requerido.
        /// </summary>
        internal static string Registration_TipoUGEL_Requerido {
            get {
                return ResourceManager.GetString("Registration_TipoUGEL_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops! Error del sistema, por favor contacte al administrador.
        /// </summary>
        internal static string Sistema_Error_Mensaje_Titulo {
            get {
                return ResourceManager.GetString("Sistema_Error_Mensaje_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Apellido Materno del Docente es requerido.
        /// </summary>
        internal static string Update_ApellidoMaterno_Requerido {
            get {
                return ResourceManager.GetString("Update_ApellidoMaterno_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Apellido Paterno del Docente es requerido.
        /// </summary>
        internal static string Update_ApellidoPaterno_Requerido {
            get {
                return ResourceManager.GetString("Update_ApellidoPaterno_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI del Docente es requerido.
        /// </summary>
        internal static string Update_DNIDocente_Requerido {
            get {
                return ResourceManager.GetString("Update_DNIDocente_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los Nombres del Docente son requeridos.
        /// </summary>
        internal static string Update_Nombres_Requerido {
            get {
                return ResourceManager.GetString("Update_Nombres_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificacion de Resolucion guardada satisfactoriamente.
        /// </summary>
        internal static string Update_Satisfactorio_Mensaje {
            get {
                return ResourceManager.GetString("Update_Satisfactorio_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificacion de Resolucion.
        /// </summary>
        internal static string Update_Satisfactorio_Mensaje_Titulo {
            get {
                return ResourceManager.GetString("Update_Satisfactorio_Mensaje_Titulo", resourceCulture);
            }
        }
    }
}
