//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGELNorte.Resoluciones.Presentation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UGELNorte.Resoluciones.Presentation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminacion de Resolucion satisfactoria.
        /// </summary>
        internal static string Delete_Satisfactorio_Mensaje {
            get {
                return ResourceManager.GetString("Delete_Satisfactorio_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminacion de Resolucion.
        /// </summary>
        internal static string Delete_Satisfactorio_Mensaje_Titulo {
            get {
                return ResourceManager.GetString("Delete_Satisfactorio_Mensaje_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porfavor revisar lo siguiente.
        /// </summary>
        internal static string Error_Mensaje_Cabecera {
            get {
                return ResourceManager.GetString("Error_Mensaje_Cabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta resolucion ya existe en D:\Resoluciones.
        /// </summary>
        internal static string Importacion_PDF_Error {
            get {
                return ResourceManager.GetString("Importacion_PDF_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Importacion de Resolucion .PDF.
        /// </summary>
        internal static string Importacion_PDF_Error_Titulo {
            get {
                return ResourceManager.GetString("Importacion_PDF_Error_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La importacion se realizo con exito, Esta se añadio en: D:\Resoluciones.
        /// </summary>
        internal static string Importacion_PDF_Satisfactoria {
            get {
                return ResourceManager.GetString("Importacion_PDF_Satisfactoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importacion de Resolucion .PDF.
        /// </summary>
        internal static string Importacion_PDF_Satisfactoria_Titulo {
            get {
                return ResourceManager.GetString("Importacion_PDF_Satisfactoria_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Concepto es requerido.
        /// </summary>
        internal static string Registration_Concepto_Requerido {
            get {
                return ResourceManager.GetString("Registration_Concepto_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El DNI es requerido.
        /// </summary>
        internal static string Registration_DNI_Requerido {
            get {
                return ResourceManager.GetString("Registration_DNI_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede registrar la Resolucion.
        /// </summary>
        internal static string Registration_Error_Mensaje {
            get {
                return ResourceManager.GetString("Registration_Error_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Registro de Resolucion.
        /// </summary>
        internal static string Registration_Error_Mensaje_Titulo {
            get {
                return ResourceManager.GetString("Registration_Error_Mensaje_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Expediente Judicial es requerido.
        /// </summary>
        internal static string Registration_ExpedienteJudicial_Requerido {
            get {
                return ResourceManager.GetString("Registration_ExpedienteJudicial_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Nombre de la Institucion Educativa es requerido.
        /// </summary>
        internal static string Registration_IIEE_Requerido {
            get {
                return ResourceManager.GetString("Registration_IIEE_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Monto es requerido.
        /// </summary>
        internal static string Registration_Monto_Requerido {
            get {
                return ResourceManager.GetString("Registration_Monto_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Numero de Proyecto es requerido.
        /// </summary>
        internal static string Registration_NroProyecto_Requerido {
            get {
                return ResourceManager.GetString("Registration_NroProyecto_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Numero de Resolucion es requerido.
        /// </summary>
        internal static string Registration_NroResolucion_Requerido {
            get {
                return ResourceManager.GetString("Registration_NroResolucion_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Resolucion guardado satisfactoriamente.
        /// </summary>
        internal static string Registration_Satisfactorio_Mensaje {
            get {
                return ResourceManager.GetString("Registration_Satisfactorio_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Resolucion.
        /// </summary>
        internal static string Registration_Satisfactorio_Mensaje_Titulo {
            get {
                return ResourceManager.GetString("Registration_Satisfactorio_Mensaje_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Sentencia es requerida.
        /// </summary>
        internal static string Registration_Sentencia_Requerido {
            get {
                return ResourceManager.GetString("Registration_Sentencia_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Situacion es requerida.
        /// </summary>
        internal static string Registration_Situacion_Requerido {
            get {
                return ResourceManager.GetString("Registration_Situacion_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Tipo de Resolucion es requerido.
        /// </summary>
        internal static string Registration_TipoResolucion_Requerido {
            get {
                return ResourceManager.GetString("Registration_TipoResolucion_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Tipo de UGEL es requerido.
        /// </summary>
        internal static string Registration_TipoUGEL_Requerido {
            get {
                return ResourceManager.GetString("Registration_TipoUGEL_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Error del sistema, por favor contacte al administrador.
        /// </summary>
        internal static string Sistema_Error_Mensaje_Titulo {
            get {
                return ResourceManager.GetString("Sistema_Error_Mensaje_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Apellido Materno del Docente es requerido.
        /// </summary>
        internal static string Update_ApellidoMaterno_Requerido {
            get {
                return ResourceManager.GetString("Update_ApellidoMaterno_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Apellido Paterno del Docente es requerido.
        /// </summary>
        internal static string Update_ApellidoPaterno_Requerido {
            get {
                return ResourceManager.GetString("Update_ApellidoPaterno_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El DNI del Docente es requerido.
        /// </summary>
        internal static string Update_DNIDocente_Requerido {
            get {
                return ResourceManager.GetString("Update_DNIDocente_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los Nombres del Docente son requeridos.
        /// </summary>
        internal static string Update_Nombres_Requerido {
            get {
                return ResourceManager.GetString("Update_Nombres_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificacion de Resolucion guardada satisfactoriamente.
        /// </summary>
        internal static string Update_Satisfactorio_Mensaje {
            get {
                return ResourceManager.GetString("Update_Satisfactorio_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificacion de Resolucion.
        /// </summary>
        internal static string Update_Satisfactorio_Mensaje_Titulo {
            get {
                return ResourceManager.GetString("Update_Satisfactorio_Mensaje_Titulo", resourceCulture);
            }
        }
    }
}
